config/routes.rb
Rails.application.routes.draw do

  root to: "questions#index"
  
  resources :tags, only: [:index]
  resources :questions, only: [:index, :show]
  resources :users, only: [:index, :show]
  resources :categories, only: [:index]


  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/audio_file.rb
class AudioFile < QuranApiRecord
  belongs_to :resource, polymorphic: true
  belongs_to :recitation

  serialize :segments
end

app/models/author.rb
class Author < QuranApiRecord
  has_many :translated_names, as: :resource
  has_many :resource_contents
end

app/models/chapter.rb
class Chapter < QuranApiRecord
  has_many :verses, inverse_of: :chapter
  has_many :translated_names, as: :resource
  has_many :chapter_infos

  serialize :pages

  alias_method :name, :id
end

app/models/chapter_info.rb
class ChapterInfo < QuranApiRecord
  belongs_to :chapter
  belongs_to :language
  belongs_to :resource_content
end

app/models/char_type.rb
class CharType < QuranApiRecord
  belongs_to :parent, class_name: 'CharType'
  has_many :children, class_name: 'CharType', foreign_key: 'parent_id'
end

app/models/data_source.rb
class DataSource < QuranApiRecord
  has_many :resource_contents
end

app/models/foot_note.rb
class FootNote < QuranApiRecord
  belongs_to :resource, polymorphic: true
  belongs_to :language
  belongs_to :resource_content
end

app/models/image.rb
#class Image < QuranApiRecord
#end

app/models/language.rb
class Language < QuranApiRecord
  has_many :translated_names, as: :resource
end

app/models/media_content.rb
class MediaContent < QuranApiRecord
  belongs_to :resource, polymorphic: true
  belongs_to :language
  belongs_to :resource_content

  validates :url, :resource, presence: true

  after_create :update_embed_code_and_metadata

  protected
  def update_embed_code_and_metadata
    video = VideoInfo.new(self.url.to_s, referer: 'https://quran.com/')

    if video.available?
      #self.duration = video.duration
      self.embed_text = video.embed_code(url_attributes: url_attributes(video.provider))
      self.provider = video.provider
      self.save
    end
  rescue Exception => e
    nil
  end

  def url_attributes(provider)
    case provider.to_s.downcase
      when 'dailymotion'
        {skin: 'default', autoplay: 1, no_tabs: 0}
      when 'youtube'
        {enablejsapi: 1, wmode: 'transparent', iv_load_policy: 3, origin: 'https://quran.com', rel: 0, autohide: 1, autoplay: 1}
      else
        {}
    end
  end
end

app/models/recitation.rb
class Recitation < QuranApiRecord
  belongs_to :reciter
  belongs_to :resource_content
  belongs_to :recitation_style
end

app/models/reciter.rb
class Reciter < QuranApiRecord
  has_many :translated_names, as: :resource
end

app/models/tafsir.rb
class Tafsir < QuranApiRecord
  belongs_to :verse
  belongs_to :language
  belongs_to :resource_content
  has_many :foot_notes, as: :resource
end

app/models/translation.rb
class Translation < QuranApiRecord
  belongs_to :resource, polymorphic: true
  belongs_to :language
  belongs_to :resource_content
  has_many :foot_notes, as: :resource
end

app/models/verse.rb
class Verse < QuranApiRecord
  belongs_to :chapter, inverse_of: :verses, counter_cache: true
  has_many :tafsirs
  has_many :words
  has_many :media_contents, as: :resource
  has_many :translations, as: :resource
  has_many :transliterations, as: :resource
  has_many :audio_files, as: :resource
  has_many :recitations, through: :audio_files
end

app/models/word.rb
class Word < QuranApiRecord
  belongs_to :verse
  belongs_to :char_type
  has_many :translations, as: :resource
  has_many :transliterations, as: :resource
  has_many :audio_files, as: :resource
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>QuranComCommunity</title>
    <%= csrf_meta_tags %>

    <%= render "shared/header_scripts" %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body class="home page-template page-template-page-questions page-template-page-questions-php page page-id-12 cbp-spmenu-push">

  <%= render "shared/top_navs" %>

  <div class="container-fluid">
    <div class="row">

      <%= render "shared/header" %>

      <%= render "shared/left_sidebar" %>
      <!-- END LEFT-SIDEBAR -->
    <div itemtype="http://schema.org/ItemList" class="col-md-8 main-content">
      <link itemprop="url" href="http://qaengine.enginethemes.com" style="display: none;"/>
      <div class="clearfix"></div>

      <%= yield %>

      <div class="clearfix"></div>
    </div>

      <%= render "shared/right_sidebar" %>
    </div><!-- END ROW -->
  </div>





<<<<<<< HEAD
  <%= render "popups/login" %>
=======

>>>>>>> e25a983c86849433a0c1daddfa97edbd4665ec3c
  <%= render "shared/footer_scripts" %>
  </body>
</html>

app/views/popups/_all_popups.html.erb
<!-- MODAL LOGIN / REGISTER -->
<div class="modal fade modal-submit-questions" id="login_register" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true"><i class="fa fa-times"></i></button>
        <h4 class="modal-title modal-title-sign-in" id="myModalLabel">Sign In</h4>
      </div>
      <div class="modal-body">
        <form id="signin_form" class="form_modal_style">
          <label for="username">
            Username or Email					</label>
          <input type="text" class="email_user"  name="username" id="username" />

          <label for="password">
            Password					</label>
          <input type="password" class="password_user" id="password" name="password">
          <div class="clearfix"></div>
          <input type="submit" name="submit" value="Sign in" class="btn-submit">
          <a href="javascript:void(0)" class="link_forgot_pass">Forgot password</a>
          <div class="submit-block">
            <a href="javascript:void(0)" class="link_sign_up">Sign up here</a><span>or sign in with</span>

            <ul class="social-icon clearfix">
              <!-- google plus login -->
              <!-- twitter plus login -->
              <!-- facebook plus login -->
            </ul>
          </div>

        </form>

        <form id="signup_form" class="form_modal_style">
          <label for="username">
            Username					</label>
          <input type="text" class="name_user" name="username" id="username" />

          <label for="email">
            Email					</label>
          <input type="text" class="email_user" name="email" id="email" />

          <label for="password1">
            Password					</label>
          <input type="password" class="password_user_signup" id="password1" name="password" />

          <label for="re_password">
            Retype Password					</label>
          <input type="password" class="repeat_password_user_signup" id="re_password" name="re_password" />


          <div class="clearfix"></div>
          <div class="gg-captcha">
          </div>
          <input type="submit" name="submit" value="Sign up" class="btn-submit">
          <a href="javascript:void(0)" class="link_sign_in">Sign in</a>

          <div class="clearfix"></div>

          <p class="policy-sign-up">
            By clicking "Sign up" you indicate that you have read and agree to the <a target="_blank" href="http://qaengine.enginethemes.com/privacy/">privacy policy</a> and <a target="_blank" href="http://qaengine.enginethemes.com/term/">terms of service.</a>					</p>
        </form>

        <form id="forgotpass_form" class="form_modal_style collapse">
          <label>Enter your email here</label>
          <input type="text" class="name_user" name="email" id="email" />
          <input type="submit" name="submit" value="Send" class="btn-submit">
          <a href="javascript:void(0)" class="return_link_sign_in">Sign in</a>
        </form>

      </div>
    </div>
  </div>
</div>	<!-- MODAL LOGIN / REGISTER -->

<!-- MODAL RESET PASSWORD -->
<div class="modal fade modal-submit-questions" id="reset_password" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true"><i class="fa fa-times"></i></button>
        <h4 class="modal-title modal-title-sign-in" id="myModalLabel">Reset Password</h4>
      </div>
      <div class="modal-body">

        <form id="resetpass_form" class="form_modal_style">
          <input type="hidden" id="user_login" name="user_login" value="" />
          <input type="hidden" id="user_key" name="user_key" value="">
          <label>Enter your new password here</label>
          <input type="password" class="name_user" name="new_password" id="new_password" />
          <input type="password" class="name_user" name="re_new_password" id="re_new_password" />
          <input type="submit" name="submit" value="Reset" class="btn-submit">
        </form>

      </div>
    </div>
  </div>
</div>	<!-- MODAL RESET PASSWORD -->

<!-- MODAL EDIT PROFILE / CHANGE PASS -->
<div class="modal fade modal-edit-profile" id="edit_profile" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true"><i class="fa fa-times"></i></button>
        <h4 class="modal-title" id="myModalLabel">Edit Profile</h4>
      </div>
      <div class="modal-body">
        <div class="author-edit" id="user_avatar_container">
                    <span class="author-avatar image" id="user_avatar_thumbnail">
                                            </span>
          <div class="edit-info-avatar">
            <a href="javascript:void(0);" class="upload-avatar-btn" id="user_avatar_browse_button">
              Upload New Avatar                        </a>
            <a href="javascript:void(0);" class="link_change_password">Change Password</a>
            <a href="javascript:void(0);" class="link_change_profile">Change Profile</a>
          </div>
          <span class="et_ajaxnonce" id="750356c220"></span>
        </div>

        <form id="submit_edit_profile" class="form_modal_style edit_profile_form">
          <label>Full name</label>
          <input type="text" class="submit-input" maxlength="40" id="display_name" name="display_name">

          <label>Location</label>
          <input type="text" class="submit-input" maxlength="40" id="user_location" name="user_location">

          <label>Facebook</label>
          <input type="text" class="submit-input" maxlength="80" id="user_facebook" name="user_facebook">

          <label>Twitter</label>
          <input type="text" class="submit-input" maxlength="80" id="user_twitter" name="user_twitter">

          <label>Google+</label>
          <input type="text" class="submit-input" maxlength="80" id="user_gplus" name="user_gplus">

          <label>Email</label>
          <input type="text" class="submit-input" id="user_email" name="user_email">

          <div class="clearfix"></div>

          <label>About me</label>
          <textarea  maxlength="350" class="submit-textarea" id="description" name="description"></textarea>
          <input type="checkbox" name="show_email"  id="show_email" />
          <label for="show_email" class="checkbox-email">
            Make this email public.                        </label>
          <div class="clearfix"></div>

          <input type="submit" name="submit" value="Update Profile" class="btn-submit update_profile">
        </form>

        <form id="submit_edit_password" class="form_modal_style edit_password_form">
          <label>Old Password</label>
          <input type="password" class="submit-input" id="old_password" name="old_password">
          <label>New Password</label>
          <input type="text" class="submit-input input-password" id="new_password1" name="new_password">
          <label>Repeat New Password</label>
          <input type="text" class="submit-input input-password" id="re_password" name="re_password">
          <input type="submit" name="submit" value="Change Password" class="btn-submit update_profile">
        </form>

      </div>
    </div>
  </div>
</div>	<!-- MODAL UPLOAD IMAGE -->

app/views/popups/_login.html.erb
<div class="modal fade modal-submit-questions" id="login_register" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true"><i class="fa fa-times"></i></button>
        <h4 class="modal-title modal-title-sign-in" id="myModalLabel">Sign In</h4>
      </div>
      <div class="modal-body">
        <form id="signin_form" class="form_modal_style">
          <label for="username">
            Username or Email					</label>
          <input type="text" class="email_user" name="username" id="username">

          <label for="password">
            Password					</label>
          <input type="password" class="password_user" id="password" name="password">
          <div class="clearfix"></div>
          <input type="submit" name="submit" value="Sign in" class="btn-submit">
          <a href="javascript:void(0)" class="link_forgot_pass">Forgot password</a>
          <div class="submit-block">
            <a href="javascript:void(0)" class="link_sign_up">Sign up here</a><span>or sign in with</span>

            <ul class="social-icon clearfix">
              <!-- google plus login -->
              <!-- twitter plus login -->
              <!-- facebook plus login -->
            </ul>
          </div>

        </form>

        <form id="signup_form" class="form_modal_style">
          <label for="username">
            Username					</label>
          <input type="text" class="name_user" name="username" id="username">

          <label for="email">
            Email					</label>
          <input type="text" class="email_user" name="email" id="email">

          <label for="password1">
            Password					</label>
          <input type="password" class="password_user_signup" id="password1" name="password">

          <label for="re_password">
            Retype Password					</label>
          <input type="password" class="repeat_password_user_signup" id="re_password" name="re_password">


          <div class="clearfix"></div>
          <div class="gg-captcha">
          </div>
          <input type="submit" name="submit" value="Sign up" class="btn-submit">
          <a href="javascript:void(0)" class="link_sign_in">Sign in</a>

          <div class="clearfix"></div>

          <p class="policy-sign-up">
            By clicking "Sign up" you indicate that you have read and agree to the <a target="_blank" href="http://qaengine.enginethemes.com/privacy/">privacy policy</a> and <a target="_blank" href="http://qaengine.enginethemes.com/term/">terms of service.</a>					</p>
        </form>

        <form id="forgotpass_form" class="form_modal_style collapse">
          <label>Enter your email here</label>
          <input type="text" class="name_user" name="email" id="email">
          <input type="submit" name="submit" value="Send" class="btn-submit">
          <a href="javascript:void(0)" class="return_link_sign_in">Sign in</a>
        </form>

      </div>
    </div>
  </div>
</div>	<!-- MODAL LOGIN / REGISTER -->

app/views/shared/_header.html.erb
<header id="header">
  <div class="col-md-2 col-xs-2" id="logo">
    <a href="http://qaengine.enginethemes.com">
      <img src="https://cdn.enginethemes.com/qaengine/source/wp-content/themes/qaengine/img/logo.png">
    </a>
  </div><!-- logo -->
  <div id="menu_qa" class="col-md-8 col-xs-8">
    <div class="header-menu">
      <ul>
        <li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-home current-menu-item page_item page-item-12 current_page_item menu-item-20 active "><a href="http://qaengine.enginethemes.com/">Home</a></li>
        <li class="menu-item menu-item-type-post_type menu-item-object-page current-menu-ancestor current-menu-parent current_page_parent current_page_ancestor menu-item-has-children menu-item-114"><a href="http://qaengine.enginethemes.com/about-us/">About us</a>
          <ul class="sub-menu">
            <li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-2188"><a href="http://qaengine.enginethemes.com/users/">Users</a></li>
            <li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-home current-menu-item page_item page-item-12 current_page_item menu-item-2189 active "><a href="http://qaengine.enginethemes.com/">Questions Listing</a></li>
          </ul>
        </li>
        <li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-1866"><a href="http://qaengine.enginethemes.com/blog/">Blog</a></li>
        <li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-21"><a href="http://qaengine.enginethemes.com/term/">Term</a></li>
        <li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-25"><a href="http://qaengine.enginethemes.com/contact/">Contact</a></li>
      </ul>
    </div><!-- menu -->
    <div class="header-search-wrapper">
      <section class="buttonset">
        <button id="showLeftPush"><i class="fa fa-question"></i></button>
        <button id="showRightPush"><i class="fa fa-bar-chart-o"></i></button>

        <!-- <button id="showLeft"><i class="fa fa-question"></i></button>
                    <button id="showRight"><i class="fa fa-bar-chart-o"></i></button> -->
        <button id="showTop"><i class="fa fa-list"></i></button>
      </section>
      <form id="header_search" method="GET" action="http://qaengine.enginethemes.com" class="disable-mobile-search">
        <input type="text" name="keyword" required value="" placeholder="Enter Keywords" autocomplete="off" />
        <i class="fa fa-search"></i>
        <div id="search_preview" class="search-preview empty"></div>
      </form>
    </div><!-- search -->
  </div>
  <div id="login_qa" class="col-md-2 col-xs-2 btn-group ">

    <a class="login-url" href="javascript:void(0)" data-toggle="modal">
      Login or Register						</a>

  </div><!-- avatar -->
</header><!-- END HEADER -->

app/views/shared/_header_scripts.html.erb
<link rel="shortcut icon" href=""/>
<link href='//fonts.googleapis.com/css?family=Lato:400,700&subset=latin,cyrillic,cyrillic-ext,vietnamese,latin-ext' rel='stylesheet' type='text/css'>
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<!--[if lt IE 9]>
<script src="js/html5.js"></script>
<![endif]-->		<script type="text/javascript">
  ae_globals = {"ajaxURL":"http:\/\/qaengine.enginethemes.com\/wp-admin\/admin-ajax.php","imgURL":"http:\/\/qaengine.enginethemes.com\/wp-content\/themes\/qaengine\/img\/","posts_per_page":"12","homeURL":"http:\/\/qaengine.enginethemes.com","user_confirm":0,"pending_questions":0,"pending_answers":0,"introURL":"http:\/\/qaengine.enginethemes.com\/intro-2\/","gplus_client_id":false,"plupload_config":{"max_file_size":"3mb","url":"http:\/\/qaengine.enginethemes.com\/wp-admin\/admin-ajax.php","flash_swf_url":"http:\/\/qaengine.enginethemes.com\/wp-includes\/js\/plupload\/plupload.flash.swf","silverlight_xap_url":"http:\/\/qaengine.enginethemes.com\/wp-includes\/js\/plupload\/plupload.silverlight.xap"}}		</script>
<link rel='dns-prefetch' href='//s.w.org' />
<link rel="alternate" type="application/rss+xml" title="QA Engine - Enginethemes &raquo; Feed" href="http://qaengine.enginethemes.com/feed/" />
<link rel="alternate" type="application/rss+xml" title="QA Engine - Enginethemes &raquo; Comments Feed" href="http://qaengine.enginethemes.com/comments/feed/" />
<link rel="alternate" type="application/rss+xml" title="QA Engine - Enginethemes &raquo; Questions Listing Comments Feed" href="http://qaengine.enginethemes.com/questions-listing/feed/" />

<script type="text/javascript">
  window._wpemojiSettings = {"baseUrl":"https:\/\/s.w.org\/images\/core\/emoji\/2.2.1\/72x72\/","ext":".png","svgUrl":"https:\/\/s.w.org\/images\/core\/emoji\/2.2.1\/svg\/","svgExt":".svg","source":{"concatemoji":"http:\/\/qaengine.enginethemes.com\/wp-includes\/js\/wp-emoji-release.min.js?ver=1483691855"}};
  !function(a,b,c){function d(a){var b,c,d,e,f=String.fromCharCode;if(!k||!k.fillText)return!1;switch(k.clearRect(0,0,j.width,j.height),k.textBaseline="top",k.font="600 32px Arial",a){case"flag":return k.fillText(f(55356,56826,55356,56819),0,0),!(j.toDataURL().length<3e3)&&(k.clearRect(0,0,j.width,j.height),k.fillText(f(55356,57331,65039,8205,55356,57096),0,0),b=j.toDataURL(),k.clearRect(0,0,j.width,j.height),k.fillText(f(55356,57331,55356,57096),0,0),c=j.toDataURL(),b!==c);case"emoji4":return k.fillText(f(55357,56425,55356,57341,8205,55357,56507),0,0),d=j.toDataURL(),k.clearRect(0,0,j.width,j.height),k.fillText(f(55357,56425,55356,57341,55357,56507),0,0),e=j.toDataURL(),d!==e}return!1}function e(a){var c=b.createElement("script");c.src=a,c.defer=c.type="text/javascript",b.getElementsByTagName("head")[0].appendChild(c)}var f,g,h,i,j=b.createElement("canvas"),k=j.getContext&&j.getContext("2d");for(i=Array("flag","emoji4"),c.supports={everything:!0,everythingExceptFlag:!0},h=0;h<i.length;h++)c.supports[i[h]]=d(i[h]),c.supports.everything=c.supports.everything&&c.supports[i[h]],"flag"!==i[h]&&(c.supports.everythingExceptFlag=c.supports.everythingExceptFlag&&c.supports[i[h]]);c.supports.everythingExceptFlag=c.supports.everythingExceptFlag&&!c.supports.flag,c.DOMReady=!1,c.readyCallback=function(){c.DOMReady=!0},c.supports.everything||(g=function(){c.readyCallback()},b.addEventListener?(b.addEventListener("DOMContentLoaded",g,!1),a.addEventListener("load",g,!1)):(a.attachEvent("onload",g),b.attachEvent("onreadystatechange",function(){"complete"===b.readyState&&c.readyCallback()})),f=c.source||{},f.concatemoji?e(f.concatemoji):f.wpemoji&&f.twemoji&&(e(f.twemoji),e(f.wpemoji)))}(window,document,window._wpemojiSettings);
</script>

<style type="text/css">
  img.wp-smiley,
  img.emoji {
    display: inline !important;
    border: none !important;
    box-shadow: none !important;
    height: 1em !important;
    width: 1em !important;
    margin: 0 .07em !important;
    vertical-align: -0.1em !important;
    background: none !important;
    padding: 0 !important;
  }
</style>


<link rel='https://api.w.org/' href='http://qaengine.enginethemes.com/wp-json/' />
<link rel="EditURI" type="application/rsd+xml" title="RSD" href="http://qaengine.enginethemes.com/xmlrpc.php?rsd" />
<link rel="wlwmanifest" type="application/wlwmanifest+xml" href="http://qaengine.enginethemes.com/wp-includes/wlwmanifest.xml" />
<meta name="generator" content="WordPress 4.7.1" />
<link rel="canonical" href="http://qaengine.enginethemes.com/" />
<link rel='shortlink' href='http://qaengine.enginethemes.com/' />
<link rel="alternate" type="application/json+oembed" href="http://qaengine.enginethemes.com/wp-json/oembed/1.0/embed?url=http%3A%2F%2Fqaengine.enginethemes.com%2F" />
<link rel="alternate" type="text/xml+oembed" href="http://qaengine.enginethemes.com/wp-json/oembed/1.0/embed?url=http%3A%2F%2Fqaengine.enginethemes.com%2F&#038;format=xml" />

app/views/shared/_left_sidebar.html.erb
<div class="col-md-12 col-xs-12" id="header_sidebar">
</div>
<div class="col-md-2 disable-mobile left-sidebar">
  <ul>
    <li class="widget widget-btn">
      <button type="button" data-toggle="modal" class="action ask-question">
        <i class="fa fa-plus"></i> ASK A QUESTION                </button>
    </li><!-- END BUTTON MODAL QUESTION -->
    <li class="widget widget-menus">
      <div class="menu-left-menu-container"><ul id="menu-left-menu-1" class="menu">
        <li class="fa-question-circle menu-item menu-item-type-custom menu-item-object-custom menu-item-1765">
          <%= link_to root_path do %>
              <i class="fa fa-question-circle"></i>Questions
          <% end %>
        </li>
        <li class="fa-tags menu-item menu-item-type-post_type menu-item-object-page menu-item-183 <%= 'active' if controller_name == "tags" %>">
          <%= link_to tags_path do %>
              <i class="fa fa-tags"></i>Tags
          <% end %>
        </li>
        <li class="fa-trophy menu-item menu-item-type-post_type menu-item-object-page menu-item-18"><a href="#_"><i class="fa fa-trophy"></i>Badges</a></li>
        <li class="fa-th-list menu-item menu-item-type-post_type menu-item-object-page menu-item-1742">
          <%= link_to categories_path do %>
              <i class="fa fa-th-list"></i>Categories
          <% end %>
        </li>
        <li class="fa-users menu-item menu-item-type-post_type menu-item-object-page menu-item-1743">
          <%= link_to users_path do %>
              <i class="fa fa-users"></i>Users
          <% end %>
        </li>

      </ul></div>            </li><!-- END LEFT MENU -->
  </ul>
  <div class="clearfix"></div>
  <div class="copyright">
    &copy;2017  <br>
    <a href="http://qaengine.enginethemes.com/term/">Terms & Privacy</a>
  </div>
</div>